version: '2.4'

services:
  manager:
    build:
      context: ./instancer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: "unless-stopped"
    ports:
      - "1337:1337"
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
